### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Reaper10** [tim-janik/anklang#2]
I want want to help with icon and splash screen.  But I'm not sure what to do with the name like ANKLANG. Unlike the name beast it was easy.

**Comment by tim-janik** [comment]
Here is the favicon Anklang currently uses.

https://raw.githubusercontent.com/tim-janik/anklang/trunk/ui/assets/favicon.svg

Do you have Linux yet, so you can test pre-releases?
If not, it'll be hard to assist with anything.

**Comment by Reaper10** [comment]
i don't

> Here is the favicon Anklang currently uses.
> 
> https://raw.githubusercontent.com/tim-janik/anklang/trunk/ui/assets/favicon.svg
> 
> Do you have Linux yet, so you can test pre-releases?
> If not, it'll be hard to assist with anything.

I don't. Will it ever be on windows? Did you like any of [my work? ](https://github.com/Reaper10/ui-kit-for-the-beast-daw)? [I'm starting over.](https://github.com/Reaper10/anklang-icons) I don't what to do for the app icon or splash screen

**Comment by tim-janik** [comment]
Thank you for taking an interest in the project.
Note, submissions and discussions are only helpful if all participants can test and evaluate the software for themselves.
Anklang makes this as easy as possible by providing binary AppImages, however using Linux is a fundamental technical requirement at this point.

About the paintings you provided, we don't see how the Anklang UI could benefit from your ideas at the moment.
Anklang uses the [Material Icon](https://material.io/resources/icons/?style=baseline) set and sometimes [ForkAwesome](https://forkaweso.me/Fork-Awesome/) for now. Sometimes an icon or cursor is missing, but submissions in those cases need to fit into the existing styles (i.e. similar to Material Design Icons). Consistently styled UIs need icons of appropriate sizes (e.g. 24x24 or 32x32 pixels, see existing icon fonts), clear metaphors  and some kind of overarching design guidance. 

As mentioned in [issue 141](https://github.com/tim-janik/beast/issues/141), there are resources online that provide guidance with icon development:

https://community.kde.org/Guidelines_and_HOWTOs/Icon_Workflow_Tips
https://teams.pages.gitlab.gnome.org/Design/hig-www/guidelines/app-icons.html
http://turbomilk.com/blog/cookbook/icon_design/10_mistakes_in_icon_design/
https://commons.wikimedia.org/wiki/Comparison_of_icon_sets

Related, GNOME and KDE are both projects that may benefit from someone active in icon design, as are other projects. The above Wikimedia page has gaps for instance. 

Whether Anklang is ever ported to Windows or other platforms depends on someone making an effort. Anklang will certainly be easier to port than Beast was (and there was a Beast Windows porting attempt more than a decade ago), because the UI is already using cross-platform technologies. However it is not on our current TODO list, so it'd take someone else to put in the work.

**Comment by Reaper10** [comment]
@tim-janik sorry for wasting your time
